export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";
export const CREATE_EVENT_LOADING = "CREATE_EVENT_LOADING";

export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const LOAD_EVENTS_FAIL = "LOAD_EVENTS_FAIL";
export const LOAD_EVENTS_LOADING = "LOAD_EVENTS_LOADING";


export const CLEAR_ERRORS = 'CLEAR_ERRORS'; 